from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent

SECRET_KEY = "proctoring-tool-dev-key"
ADMIN_PASSWORD = "admin123"

START_MATCH_THRESHOLD = 0.84
LIVE_MATCH_THRESHOLD = 0.74
LIVE_IDENTITY_MISMATCH_STREAK_THRESHOLD = 5
SIDEWAYS_THRESHOLD = 0.36

REGISTRATION_CENTER_MAX = 0.10
REGISTRATION_SIDE_MIN = 0.12
REGISTRATION_MIN_FACE_AREA_RATIO = 0.07

REGISTERED_FACES_FILE = BASE_DIR / "registered_faces.json"
MIN_DOWNLOAD_MBPS = 2.0
LOW_LIGHT_MEAN_THRESHOLD = 60.0
PHONE_VISIBLE_STREAK_THRESHOLD = 1
PHONE_DETECTOR_MODEL_PATH = str(BASE_DIR / "yolo11n.pt")
PHONE_DETECTOR_CONFIDENCE = 0.10
PHONE_DETECTOR_IOU = 0.45
PHONE_DETECTOR_IMAGE_SIZE = 416
PHONE_DETECTOR_FRAME_SKIP = 1
PHONE_DETECTOR_MAX_DIM = 960
VIOLATION_EVENTS_FILE = BASE_DIR / "violation_events.json"
VIOLATION_CAPTURES_DIR = BASE_DIR / "static" / "violation_captures"
MAX_VIOLATION_EVENTS_PER_USER = 120
VIOLATION_CAPTURE_COOLDOWN_SECONDS = 3.0

MOBILE_UA_TOKENS = (
    "android",
    "iphone",
    "ipad",
    "ipod",
    "windows phone",
    "mobile",
    "opera mini",
    "iemobile",
)
